fix: Handle cleanup of workdir better
Sometimes, we see random errors during the clean.

```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':myplugin:testServer' (registered by plugin 'org.jenkins-ci.jpi2')
  Caused by: org.gradle.api.GradleException: Failed to delete file from temporary Jenkins work directory /path/myplugin/build/tmp/testServer/jenkins-work-9064908567013095199/monitoring/_MacBook-5FCGQ
  Caused by: java.nio.file.DirectoryNotEmptyException: /path/myplugin/build/tmp/testServer/jenkins-work-9064908567013095199/monitoring/_MacBook-5FCGQ
```

This changes how we do the deletes to avoid this failure.